[versions]
accompanist = "0.24.4"
coroutines = "1.6.1"
aurora = "1.1.0"
cryptohash = "0.10.0"
kotlinx-datetime = "0.3.3"
lwjgl = "3.3.1"

[libraries]
accompanist-flowlayouts = { module = "ca.gosyer:accompanist-flowlayout", version.ref = "accompanist" }
aurora-window = { module = "org.pushing-pixels:aurora-window", version.ref = "aurora" }
aurora-component = { module = "org.pushing-pixels:aurora-component", version.ref = "aurora" }
aurora-theming = { module = "org.pushing-pixels:aurora-theming", version.ref = "aurora" }
crypto-cryptohash = { module = "com.appmattus.crypto:cryptohash", version.ref = "cryptohash" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
lwjgl-core = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-tinyfd = { module = "org.lwjgl:lwjgl-tinyfd", version.ref = "lwjgl" }