[versions]
aurora = "2.0-20230423.032104-3"
buildconfig = "4.0.4"
compose = "1.4.0"
coroutines = "1.7.1"
cryptohash = "0.10.1"
detekt = "1.23.0-RC3"
flowext = "0.6.0"
github-api = "1.314"
jna = "5.13.0"
jsystemthemedetector = "3.8"
kamel = "0.4.1"
klogging = "0.4.13"
koin = "3.4.0"
koin-compose = "1.0.1"
koin-ksp = "1.2.0"
kotlin = "1.8.20"
kotlin-csv = "1.9.0"
kotlinx-datetime = "0.4.0"
ksp = "1.8.20-1.0.11"
lwjgl = "3.3.2"
slf4j = "2.0.7"
voyager = "1.0.0-rc06"
windowstyler = "0.3.2"

[libraries]
aurora-component = { module = "org.pushing-pixels:aurora-component", version.ref = "aurora" }
aurora-theming = { module = "org.pushing-pixels:aurora-theming", version.ref = "aurora" }
aurora-window = { module = "org.pushing-pixels:aurora-window", version.ref = "aurora" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

crypto-cryptohash = { module = "com.appmattus.crypto:cryptohash", version.ref = "cryptohash" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

flowext = { module = "io.github.hoc081098:FlowExt", version.ref = "flowext" }

github-api = { module = "org.kohsuke:github-api", version.ref = "github-api" }

jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

jsystemthemedetector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jsystemthemedetector" }

kamel-image = { module = "com.alialbaali.kamel:kamel-image", version.ref = "kamel" }

klogging-jvm = { module = "io.klogging:klogging-jvm", version.ref = "klogging" }

koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-ksp" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-ksp" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

kotlincsv = { module = "com.github.doyaaaaaken:kotlin-csv", version.ref = "kotlin-csv" }

lwjgl-core = { module = "org.lwjgl:lwjgl", version.ref = "lwjgl" }
lwjgl-nativefiledialogs = { module = "org.lwjgl:lwjgl-nfd", version.ref = "lwjgl" }

slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }

windowstyler = { module = "com.mayakapps.compose:window-styler", version.ref = "windowstyler" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }